server:
  port: 0

spring:
  application:
    name: qiyun-user-service-test

  cloud:
    nacos:
      discovery:
        enabled: false

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always